### ISSUE TITLE
Possible merge with 5to6?

### ISSUE THREAD

**Issue by RReverser** [mohebifar/lebab#1]
[5to6](https://github.com/thomasloh/5to6/tree/master/src/modules) project has same goals and list of other transformations, while `xto6` supports only class transformation. My thought is that both projects would benefit from merge or collaboration.

/cc @thomasloh @benjamn

**Comment by benjamn** [comment]
I support this idea!

**Comment by goatslacker** [comment]
+1

**Comment by thomasloh** [comment]
+1. In fact there's already a movement going on for collaboration https://github.com/5to6

**Comment by xjamundx** [comment]
Yeah would love to collab. I think a lot of us all got a few transforms out and then it got hard and we stopped, but happy to work or just straight up give anyone commit rights to the https://github.com/5to6 org that wants to hack on this stuff :)

**Comment by andyhu** [comment]
+1

**Comment by xjamundx** [comment]
FYI my version of this concept is moving to https://github.com/5to6/5to6-codemod which will focus on using `jscodeshift` to actuall run the transforms. Feel free to combine or not combine with that project :)

**Comment by andyhu** [comment]
@xjamundx How about merging lebeb to 5to6?

**Comment by mohebifar** [comment]
Closing this as explained by @nene in #93.

**Comment by xjamundx** [comment]
For what it's worth https://github.com/5to6/5to6-codemod has decided to go the route of becoming a set of `jscodeshift` transforms. Easier to maintain that way, but maybe not as comprehensive as this project.
