### ISSUE TITLE
Updating lebab.io and xto6.js.org

### ISSUE THREAD

**Issue by nene** [mohebifar/lebab#103]
As I understand the http://xto6.js.org site resides in [gh-pages](https://github.com/mohebifar/lebab/tree/gh-pages) branch of this repo, but I have no idea what's the source for http://lebab.io.

- As the project name is now Lebab, we should redirect xto6.js.org to lebab.io
- We should upgrade the [Try it live!](http://lebab.io/try-it) feature in lebab.io to use the latest 1.0.0 release.

**Comment by nene** [comment]
We should also deprecate the old xto6 releases in npm, as pointed out in #56

**Comment by nene** [comment]
@mohebifar I see you have updated http://lebab.io/try-it

What about http://xto6.js.org ?

**Comment by mohebifar** [comment]
We need to find a way to redirect xto6.js.org to lebab.io somehow. We were using [js.org](https://github.com/js-org/dns.js.org) free domains. I will follow this discussion there.

Lebab.io source code is also [here](https://github.com/lebabjs/lebabjs.github.io)

**Comment by nene** [comment]
I pushed a meta-redirect to xto6.js.org site. That should at least temporarily take care of this.

Apparently [github-pages documentation](https://help.github.com/articles/redirects-on-github-pages/) tells one to use [jekyll-redirect-from plugin](https://github.com/jekyll/jekyll-redirect-from) which uses the same meta-redirect approach. So maybe that's the best we can do.

**Comment by nene** [comment]
What about deprecating the `xto6` package in npm? (See #56)

**Comment by mohebifar** [comment]
Thank you. It seems that's the only way to do this. `xto6` has also been deprecated now.
