### ISSUE TITLE
Crunch UMD wrappers

### ISSUE THREAD

**Issue by IngwiePhoenix** [mohebifar/lebab#104]
Usually, you'd find something like this

```javascript
(function(factory){
	// CommonJS/RequireJS and "native" compatibility
	if(typeof module !== "undefined" && typeof exports == "object") {
		// A commonJS/RequireJS environment
		if(typeof window != "undefined") {
			// Window and document exist, so return the factory's return value.
			module.exports = factory();
		} else {
			// Let the user give the factory a Window and Document.
			module.exports = factory;
		}
	} else {
		// Assume a traditional browser.
		window.MyModule = factory();
	}
})(function(){
    // ...
    return something;
});
```

What we want to extract is:

```
CallExpression
    -> Arguments
        -> [1]: FunctionExpression
```

And instead:

```javascript
let factory = (function() {
    // ... Might use an arrow func? ...
})();
let exports = typeof factory.default != "undefined"
    ? factory
    : {default: factory}
export exports;
```

The pattern is so common, that it should almost be possible pick up the correct argument and "paste" it into a generic template - like the one above, for example.

Do you think this could be implemented? Because with this, I would actually immediately go ahead and write a tool to mass-convert a lot of my libraries.

**Comment by nene** [comment]
This doesn't really look so generic to me. It's a fairly big chunk of code. I've seen several libraries that do this UMD thing, but there's always quite a bit of variation in the implementation. The larger the code gets, the more there are possibilities for writing it, and the harder it will be to detect by tools. (Though maybe it really is a consistently repeated pattern... I'd like to see examples from various libraries.)

Another part is that your suggested target code looks problematic. I doubt one really wants to write it like so in ES6. One should simply export his API functions/objects directly, without wrapping them to some factory. It also seems that it's not directly equivalent of the source code - exporting to global `window.MyModule` is gone, it's referencing `factory.default` which is nowhere to be found in source. But the goal of Lebab is to do only safe transformations - never changing what the program does.

Finally, this kind of thing is only used once per library. Most people don't have lots of libraries to convert, so the benefit of automating this would be negligible. Although you seem to be exceptional in this regard...

**Comment by IngwiePhoenix** [comment]
> This doesn't really look so generic to me. It's a fairly big chunk of code. I've seen several libraries that do this UMD thing, but there's always quite a bit of variation in the implementation. The larger the code gets, the more there are possibilities for writing it, and the harder it will be to detect by tools. (Though maybe it really is a consistently repeated pattern... I'd like to see examples from various libraries.)

Actually - there is. The pattern usually can be described like so:
- A function with a `factory` and an optional `root` parameter. The `factory` returns the actual module that should be exported.
- The factory takes no parameters. Some very rarely take dependencies as parameters. Eg: `module.exports = factory(require("jquery"))` and `function($)` as the argument for `factory`

Sometimes the factory is the first or second parameter, but the parameter is _always_ a function - and _one function only_.

> Another part is that your suggested target code looks problematic.

Yeah... yeah I know :). It only was meant as an example. It definitively is far, far from optimal. But all it was supposed to do was to get the point across of what I was trying to say. I am not a native english speaker, so sometiems an example serves me better than words.

> I doubt one really wants to write it like so in ES6.

And nobody ever should.

> One should simply export his API functions/objects directly, without wrapping them to some factory.

In a UMD wrapper, only the factory's contents really matter. Maybe just extracting that would do the job, but as you said in the following sentences, it doesn't perfectly make sense since the export to global scope would be lost.

> Finally, this kind of thing is only used once per library. Most people don't have lots of libraries to convert, so the benefit of automating this would be negligible.

Well - it was an idea I got when I saw that CommonJS2 style `module.exports` statements could, partially, be translated. I find that the current mix-and-match of various module styles is a pain to work with when using tiny libraries (i am rather radical about source code sizes, which usually pays me back with a good mixture of oddities) - and which is why I would like to move to ES6 modules entirely, since this is what many people, bundlers and tools are aiming for, and which I hope becomes a de-facto standard.

> Although you seem to be exceptional in this regard...

What exactly do you mean by that? o.o

**Comment by nene** [comment]
> What exactly do you mean by that? o.o

I think you answered it by yourself by explaining that you're structuring your code to lots of tiny libraries.

But yeah, this kind of transform doesn't look suitable for Lebab, as it's changing what the program does. Also the priority right now is to get down the basic support for transforming imports and exports, like recognizing named exports and RequireJS syntax.
