### ISSUE TITLE
Fails on vars defined in for-heads

### ISSUE THREAD

**Issue by webbedspace** [mohebifar/lebab#106]
See this code:
```
for (var i = 12; i >= 0; i--) {}
for (i = 12; i >= 0; i--) {}
```
This incorrectly becomes:
```
for (let i = 12; i >= 0; i--) {}
for (i = 12; i >= 0; i--) {}
```

**Comment by nene** [comment]
Thats a good catch. The `i` variable is scoped to the block, but the block doesn't consist of just the following `BlockStatement`, but of the whole `ForStatement`.

**Comment by nene** [comment]
This also revealed another bug regarding loop-heads.

Both fixed now.

Thanks once more for reporting.
