### ISSUE TITLE
Remove grunt

### ISSUE THREAD

**Issue by mohebifar** [mohebifar/lebab#109]
I suppose that we do not need any additional CLI tooling anymore as long as the tasks are not complicated that much and transpiling can be done easily using babel cli. Also, we can even run the unit tests through babel's require hook.

**Comment by nene** [comment]
Yep. And we should also upgrade to Babel 6.

**Comment by brandly** [comment]
Hey! How do you want to handle the `watch` task? [Watchman](https://www.npmjs.com/package/fb-watchman) should work, but I figured I'd ask first.

All the other tasks look like they can be easily handled without `grunt`.

**Comment by nene** [comment]
I haven't used Watchman or any other such file-watching tool, but it looks from the docs the Watchman would be a good fit. Go ahead.
