### ISSUE TITLE
Release 1.1

### ISSUE THREAD

**Issue by nene** [mohebifar/lebab#110]
There have been bunch of fixes and improvements since 1.0:

- `default-args` transform renamed to `default-param` and improved detection of various forms.
- Support for named imports and exports.
- Removed `esutils` dependency
- Fix for `let` transform #106 
- Detect `.bind(this)` when converting to arrow function #105
- Plus lots of refactoring and clean up behind the scenes.

I think it's time to get these fixes out there.

**Comment by nene** [comment]
Nice :+1:

**Comment by nene** [comment]
Just noticed that the issue for releasing 1.1.0 is also numbered #110.

**Comment by mohebifar** [comment]
Nice catch. :smile:

**Comment by signalwerk** [comment]
https://lebab.io/try-it is still the old version right?

**Comment by mohebifar** [comment]
Yes. I will update it in a few hours.

**Comment by signalwerk** [comment]
:blush: nice! Thanks a lot!
