### ISSUE TITLE
Transform whole project / folder / multiple files / overwrite file

### ISSUE THREAD

**Issue by brunolemos** [mohebifar/lebab#114]
Any way to easily do that?
I want all files to be converted and overwritten, similar to what the codeshift tool does.

**Comment by nene** [comment]
That's easy to achieve using standard UNIX tools:

```bash
for file in $(find . -name "*.js"); do
    lebab $file -o $file
done
```

**Comment by brunolemos** [comment]
Cool, thanks. Now I just have to make it work with my half es5 half es6 project :P

Any reason why it does not support a folder as input by default?

**Comment by nene** [comment]
No particular reason, just that the focus has been elsewhere.

Though my personal experience tells me, it's not so simple feature as it looks on the surface:

- Which files should we look for? Only `*.js`? What about `*.jsx`? Maybe we'll need an option for that.
- Should we also look into hidden directories? Perhaps another option.
- Should we also follow symlinks? Maybe yet another option.
- Transforming lots of files could take time. Maybe we should log some feedback messages?

...it's quite a rabbit hole.

**Comment by nene** [comment]
Hmm... perhaps I misunderstood your question...

Running Lebab with just input file given prints the result to STDOUT like any normal UNIX tool. Overwriting the file instead would be contrary to the expected UNIX practices.
