### ISSUE TITLE
lebab breaks file if it's using let already for two identically-named loop variables

### ISSUE THREAD

**Issue by mtaran-google** [mohebifar/lebab#115]
repro:
foo.js:
```js
for (let i = 0; i < 100; i++) {
  console.log(i);
}

for (let i = 0; i < 100; i++) {
  console.log(i);
}
```

running lebab over this produces:
```js
for (var i = 0 i < 100; i++) {
  console.log(i);
}

for (let i = 0; i < 100; i++) {
  console.log(i);
}
```

note the missing semicolon, and new `var`

**Comment by nene** [comment]
This is a known deficiency. The `let` transform currently treats existing `let` and `const` variables as if they were `var`. See #90.

But thanks for bringing it up, that'll help us prioritize fixing it.
