### ISSUE TITLE
let/const replacement changes behavior when modifying variable across loop iterations

### ISSUE THREAD

**Issue by mtaran-google** [mohebifar/lebab#116]
foo.js:
```js
function problematic() {
  const groups = [];
  for (i = 0; i < 10; i++) {
    var group = [];
    if (i % 2 == 0) {
      group = [];
      groups.push(group);
    }
    group.push(i)
  }
  return groups;
}
```
(simplified example; originally the declaration was just `var group;`, but the initial definition is necessary to avoid errors in the repro after the conversion)

after running lebab
```js
lebab --enable=let ~/problematic.js
function problematic() {
  const groups = [];
  for (i = 0; i < 10; i++) {
    let group = [];
    if (i % 2 == 0) {
      group = [];
      groups.push(group);
    }
    group.push(i)
  }
  return groups;
}
```

You can run the two to see their different output. The issue is that `group` gets hoisted outside the loop, and gets modified

**Comment by nene** [comment]
Sorry, but I fail to see the problem.

The transformation looks fine to me. When I run both snippets through Babel I get identical output, and accordingly both programs produce:

    [[0],[2],[4],[6],[8]]

One thing to note is that variable `i` is not defined. That will cause an error in strict mode.

**Comment by mtaran-google** [comment]
Yes, sorry, this particular one initially only had a declaration on line 2, but when converting to const that obviously didn't work well. Agree that it's working as intended here.
