### ISSUE TITLE
two const {foo} = ... assignments mean one gets turned into a `var` assignment

### ISSUE THREAD

**Issue by mtaran-google** [mohebifar/lebab#117]
```js
function test() {
    const {foo} = this.getFoo();
    const {bar} = this.getBar();
}
```
gets turned into:
```js
function test() {
    var {foo} = this.getFoo();
    const {bar} = this.getBar();
}
```

**Comment by nene** [comment]
This is another known deficiency. The let transform currently does not handle destructuring. See #90.

All known deficiencies are also listed in [README](https://github.com/mohebifar/lebab#features-and-known-limitations).
