### ISSUE TITLE
Convert commonjs module definitions

### ISSUE THREAD

**Issue by mohebifar** [mohebifar/lebab#12]
Convert commonjs module definitions to `import`, `export`

**Comment by xjamundx** [comment]
Basic CJS https://github.com/5to6/5to6/blob/master/transforms/cjs.js

Also you're welcome to steal this for AMD as well https://github.com/5to6/5to6/blob/master/transforms/amd.js (though it's just AMD => CJS) (but if you stack the transforms....)

**Comment by xjamundx** [comment]
Any interest in taking a PR?

**Comment by mohebifar** [comment]
@xjamundx Absolutely, The only thing is that we are working on a new approach for the whole process of transpiling. Thanks for sharing, I appreciate that. We will definitely use that.

**Comment by dbkaplun** [comment]
+1
