### ISSUE TITLE
Lets do a release of 1.2

### ISSUE THREAD

**Issue by nene** [mohebifar/lebab#120]
There's bunch of improvements:

- New arg-spread transform
- Various improvements and fixes for template transform
- Fix for variable name clashes with Object.prototype methods

**Comment by mohebifar** [comment]
And again it happened. Issue 120 for releasing `1.2.0`!

**Comment by nene** [comment]
We should also upgrade the live demo http://lebab.io/try-it

**Comment by mohebifar** [comment]
I will move it all to heroku now.

**Comment by nene** [comment]
Any progress on this front?

**Comment by mohebifar** [comment]
I am still waiting for heroku's response on getting a service for this.
However, I have updated the website.
