### ISSUE TITLE
Saying thanks

### ISSUE THREAD

**Issue by IonicaBizau** [mohebifar/lebab#122]
Hey @mohebifar! Just wanted to say special thanks for this! 😁  🍰  It's doing exactly what I was looking for.

I want to migrate all my modules to ES6, this will help, most probably. 🚀 
Keep up the good work! ✨

**Comment by mohebifar** [comment]
@IonicaBizau Thanks for your message.
Happy to hear that!

I want to thank @nene who has done a lot for lebab so far and has been maintaining it for months. Thank you!

**Comment by IonicaBizau** [comment]
Good job guys! 🌟 👍

**Comment by nene** [comment]
Thanks. It's good to be helpful :)
