### ISSUE TITLE
Import a field form a module

### ISSUE THREAD

**Issue by IonicaBizau** [mohebifar/lebab#123]
### ES5

```js
var parser = require("gitlog-parser").parse
```

#### Current

```js
const parser = require("gitlog-parser").parse;
```

#### Expected

```js
import { parse as parser } from "gitlog-parser";
```

Would that be possible? 💭

**Comment by mohebifar** [comment]
@nene has fixed it. Maybe you're using the live demo which is outdated.

**Comment by IonicaBizau** [comment]
@mohebifar Yes, I only played with the live demo. Sounds good then. 👍
