### ISSUE TITLE
Transpile comments

### ISSUE THREAD

**Issue by IonicaBizau** [mohebifar/lebab#124]
Looks like the JSDoc comments are currently not moved into the ES6 output:
![screen shot 2016-05-16 at 06 23 17](https://cloud.githubusercontent.com/assets/2864371/15279602/c552e7ba-1b2e-11e6-848e-f371acd0efd7.png)

**Comment by nene** [comment]
That's a bug in class transform. Closing as duplicate of #118

Feel free to open another issue if you see this problem popping up with code that doesn't have classes.
