### ISSUE TITLE
Feature Request: Detect user browser and modernize code only to where the browser currently has support

### ISSUE THREAD

**Issue by Quixomatic** [mohebifar/lebab#126]
This way if a user is using a browser that utilizes ES2015+ you will have the most optimized/modernized code available for that browser. Would require more maintenance, but would make this tool infinitely more useful.

**Comment by nene** [comment]
This is not something Lebab is meant for, and I would strongly advise against using Lebab this way.

A much better way to achieve this is to use BabelJS to write your source code to the latest ECMAScript version and compile it down to ES5+ features supported by browsers. But I think this kind of browser-detection feature even fits to the scope of BabelJS. Rather it would need to be a separate project, perhaps a Webpack plugin or something.
