### ISSUE TITLE
Lets do a release of 1.3

### ISSUE THREAD

**Issue by nene** [mohebifar/lebab#132]
The improvements since 1.2:

- Switch from Esprima to Espree parser to parse JSX.
- Support destructuring in let transform #90 
- Ignore existing let/const in let transform #90 
- Preserve comments in class transform #118

**Comment by mohebifar** [comment]
Thank you! You have done a great job.

I published the new release. Please give me your npm username if you want to do it yourself whenever you want.

**Comment by nene** [comment]
Hey, my npm username is **nene**

**Comment by mohebifar** [comment]
@nene Done.

**Comment by nene** [comment]
Nice 👍
