### ISSUE TITLE
`var bar = require('foo').default` should become `import bar from 'foo';`

### ISSUE THREAD

**Issue by graingert** [mohebifar/lebab#142]
`var bar = require('foo').default` should become `import bar from 'foo';`

```import { default as bar } from 'foo';``` is *technically* fine. But not very nice.

Edit: actually you don't know if the module 'foo' has the __es6Module property, so `import { default as bar } from 'foo'` is probably for the best

**Comment by nene** [comment]
Won't fix. As you pointed out, the current solution is technically correct and we don't have enough information to tell whether simplifying `{default to bar}` to simply `bar` would be correct thing to do.

Luckily code like this should be fairly rare.
