### ISSUE TITLE
require -> import loses module comments

### ISSUE THREAD

**Issue by graingert** [mohebifar/lebab#148]
```js
/*
 * foo
 */
 
var url = require('url');
```

becomes

```js
import url from 'url';
```

**Comment by nene** [comment]
Thanks... this comments thing needs more work.

**Comment by benjamn** [comment]
Should just be a `.comments` property on the original AST node that needs to get copied over to the new node.

**Comment by nene** [comment]
Yeah... I just need to do that systematically in every place where I replace an existing node with new one.
