### ISSUE TITLE
option to only convert functions to arrow functions when single line and passed directly to a function

### ISSUE THREAD

**Issue by graingert** [mohebifar/lebab#150]
eg:
yes:
```js
someFunctionWithCb(function(item) { return item + 1 });
```
no:
```js
var whyNoFunctionDeclarations = function (x) {
    return x + 1;
}
```
no:
```js
someFunctionWithCb(function(item) {
  var multiLineCallbackFunction = true;
  return item + 1;
});
```

**Comment by graingert** [comment]
I just find:
```js
const x = item => item + 1;
```

and
```js
someFunctionWithCb(item => {
  const multiLineCallbackFunction = true;
  return item + 1;
});
```

a bit ugly

**Comment by nene** [comment]
These feel like personal style preferences of yours. Perhaps you're also not really used to the arrow function syntax, and at first you'd like to hold back a bit. But I think that when you get more experience with it, you'll find you'd want to almost never use the old function syntax.

You could modify the arrow function transform for your liking, but I don't think it's something generally useful.

Perhaps what's bothering you is that the single-parameter syntax lacks parenthesis. You could use ESLint to enforce parenthesis: http://eslint.org/docs/rules/arrow-parens

**Comment by graingert** [comment]
Basically I'd rather use named function declarations everywhere, except where an arrow function is more readable.

This is for better stack traces

**Comment by nene** [comment]
Well... function declarations are never converted to arrow functions, and named function expressions aren't currently either: #127 (though this I'd like to get fixed).

Anyway... I don't see much benefit in implementing your feature request. That is, benefit for other users besides you. It's also not a simple addition to make - so far none of the other transforms take any options, this would be the first one, meaning quite a bit of additional complexity - so you'd really need to convince me that this is of utmost importance.

Perhaps ESLint project would be better place for such a feature as it really comes down to style preference.
