### ISSUE TITLE
Is Lebab a tool for real world?

### ISSUE THREAD

**Issue by Bamblip** [mohebifar/lebab#151]
Consider I have a very simple code using a namespace to bundle functionality under a name. I try to turn this code to ES6 using Lebab and I expect to see some classes but it seems Lebab fails to transpile this code (I saw this is a known issue #113 ).

Namespaces are a very common pattern, so what is the goal of using this kind of tools when they fail to provide new modern features of ES? I think very basic operations like changing var to const, removing "use strict" directives  and etc. are not enough to use these kind of tools to transpile a real code.
This not the only snag or limitation, consider a ES6 Code without Reflection, Proxying and etc..

**`
var Bamblip = {
  Message: ' ',
};

Bamblip.Init = function() {
  Bamblip.Message = 'Hello ';
};

Bamblip.Welcome = function(name) {
  Bamblip.Init();
  alert(Bamblip.Message + name)
}

Bamblip.Welcome('Bamblip');
`**

**Comment by mohebifar** [comment]
You need to understand that:

* Not all codes can be transformed to its equivalent in newer ES versions. 
* Some transformers [are not safe](https://github.com/mohebifar/lebab/#unsafe-transforms).
* Some transformers are so unsafe that won't be implemented.
* Lebab transforms ESx codes to ESy codes (x < y). However, it doesn't mean that you can write your code in ES5 and expect Lebab to do a magic and create a new different elegant code. That is actually what you as a programmer are supposed to do.

But what you mean by a modern code in "real world"? Let's say we have this code:

```js
fetch(URL)
.then(result => {
    dataLoaded(result);
})
.catch(error => {
    showError(error);
});
```

We have used promises. Do you think this is a modern code?

But what about this one?
```js
co(function *() {
    try {
        const result = yield fetch(URL);
        dataLoaded(result);
    } catch (error) {
        showError(result);
    }
});
```

Wait! What about this?
```js
async function () {
    try {
        const result = await fetch(URL);
        dataLoaded(result);
    } catch (error) {
        showError(result);
    }
};
```

So I think you're expecting Lebab something that is not supposed to do.

The answer is "YES". I think we're living in a world that Lebab is doing what it has to do.

**Comment by Bamblip** [comment]
In real world people use libraries and your examples are handled by them. What I really need as a programmer is to convert my own code not what libraries handle for me (Like the sample namespace code). 
Due to your response it seems Lebab is good to modernize the syntax and not the logic of the code and I believe this is not enough or even useful.

**Comment by mohebifar** [comment]
That sounds intriguing. I wonder how we can "modernize" the logic of a code. I would appreciate it if you provide more specific explanation and examples of **modernizing**
 the **logic**.

**Comment by Bamblip** [comment]
In my point of view the most important thing is to rewrite the code with OOP logic. 
OOP is not really new in ES6 its just more intuitive. People try to organize their codes with OOP attitude before and now they expect to see classes if you say you convert their code with ES6 new features.
There is a very old script [FarsiType](http://farsitype.ir/). Using Lebab to convert this code has no added value. The logic is still namespaces and not OOP and the changes Lebab applies is not exciting and It could be done by a very fast code review and some find and replaces!

**Comment by behzadsh** [comment]
@Bamblip 
> Due to your response it seems Lebab is good to modernize the syntax and not the logic of the code and I believe this is not enough or even useful.

What you said is what transpilers are. *(Take a look [here](https://en.wikipedia.org/wiki/Source-to-source_compiler).)* 

> Transpiler is a type of compiler that takes the source code of a program written in one programming language as its input and produces the equivalent source code in another programming language

Transpilers are not for changing programming logic.

**Comment by mohebifar** [comment]
@Bamblip I don't understand why you're expecting Lebab do some magic for you. Take a look at the tagline:

> Turn your ES5 code into readable ES6 (sugar-syntax). It does the opposite of what Babel does.

It's clear what it does. It's not saying that **I refactor your crappy code**!

If you have any idea of creating a tool that refactors codes, we would be happy to help as well.

**Comment by Bamblip** [comment]
@behzadsh 

> Transpilers are not for changing programming logic.

I'm not arguing about the definition of transpile. I think I made a very clear question: What is the added value of transpile ES5 to ES6 when there is logic changes in these two generations of ES? Is the output really useful in real world?
On the other hand, OOP is not really a new concept in ES but Lebab ignores that.
I repat my example on [FarsiType](http://farsitype.ir/). Transpile this code with Ledad has no added value. Not even 1%!

**Comment by Bamblip** [comment]
@mohebifar 

> I don't understand why you're expecting Lebab to do some magic for you. Take a look at the tagline

Lebab doses what it says, OK. I'm asking what is the point of having a tool like this? The problem is not about crappy, rubbish or any other type of JS codes!

**Comment by mohebifar** [comment]
If it's not useful for FarsiType, It doesn't mean that it cannot be useful at all. Your code is your code. [Check out this one](https://github.com/pixijs/pixi.js/blob/master/src/interaction/InteractionData.js). 

> Lebab transforms ESx codes to ESy codes (x < y). However, it doesn't mean that you can write your code in ES5 and expect Lebab to do a magic and create a new different elegant code. That is actually what you as a programmer are supposed to do.

Lebab eases the pain of modernizing an old code.

**Comment by Bamblip** [comment]
> Lebab eases the pain of modernizing an old code.

I hope it eases well! ;)
