### ISSUE TITLE
Programming API similar to babel.transform

### ISSUE THREAD

**Issue by alexpchin** [mohebifar/lebab#154]
Will you be implementing anything similar to:

```js
let code = babel.transform(match.code, babelOptions).code;
```

Where you can convert a string rather than passing a file?

**Comment by nene** [comment]
You mean a programming API?

There's currently an undocumented API:

```
import Transformer from "lebab";

const transformer = new Transformer({let: true, arrow: true});
transformer.run("var x = 10;"); // -> "let x = 10;"
```

I'm planning to change the API in 2.0 into a more functional form and also document it.

**Comment by mohebifar** [comment]
@nene I think he means some sort of runtime configuration file like `.babelrc`.

**Comment by alexpchin** [comment]
Ah, this is what I was looking for. Let me have a play.
I'm trying to convert a load of code blocks in a markdown so wanted to pass a string.

Thanks!

**********
Alex Chin
alexchin.co.uk, woMAPP Ltd & Microwave Ltd

  

m: +44 (0)7824 332502
e: alex@alexchin.co.uk <mailto:alex@alexchin.co.uk>
w: www.alexchin.co.uk <http://www.alexchin.co.uk/> 
 
This email and any files transmitted with it are confidential and may contain legally privileged information.  It is intended solely for use of the individual(s) or entity to whom it is addressed.  Should you receive this message in error, please notify the sender by replying to this mail or calling +44 (0)7824 332502. If you are not the intended recipient, any disclosure, distribution, reproduction, printing or reliance on the contents of this information is strictly prohibited and may be illegal.

Any views expressed by an individual within this message do not necessarily reflect the views of the company.
 
Copyright 2013 - Alex Chin

**Comment by nene** [comment]
There's now new API in Lebab 2.0. See: https://github.com/mohebifar/lebab/tree/lebab-2.0#usage
