### ISSUE TITLE
allow default configuration of flags

### ISSUE THREAD

**Issue by justin-hackin** [mohebifar/lebab#155]
Currently I'm using lebab with the Sublime Text plugin.  I converted all my files using it and then realized that nodejs 6.3.1 doesn't support commonjs import/export syntax so I want it to always be off.  The only way I could figure out how to achieve this was to modify the executable to modify the options object as such:

```
try {
  options = parseCommandLineOptions(process.argv);
  options.transforms.commonjs = false;  
}

```

A great feature would be to have a system similar to .jshintrc configs so that you could define the options you want for certain directories, or at least a global config file for options.

**Comment by nene** [comment]
You can use `--disable commonjs` to disable the commonjs transform.

I don't really see a need for config file. Our assumption has been that Lebab is a tool one doesn't really use continuously, rather you'll use it once to transform your files and then be done with it.
