### ISSUE TITLE
arguments cannot be turned into object method shorthand

### ISSUE THREAD

**Issue by lukeapage** [mohebifar/lebab#156]
```
function() {
   return {
       arguments: arguments,
   };
}
```
==>
```
function() {
   return {
       arguments,
   };
}
```
is not a valid transformation - you get parse errors

**Comment by nene** [comment]
Really? Is there some particular implementation that gives you parse error for this? Or can you point at some spec that says `arguments` is prohibited in object property shorthand?

I tried with Babel, Chrome, Node - all of them parsed it just fine. I looked at [ES6 spec](http://www.ecma-international.org/ecma-262/6.0/#sec-object-initializer) from where I found no limitation on identifier names one can use as object property shorthand. I also looked into the various limitations that strict mode places on `arguments`, but found no limitation that would apply here.

PS. The title of the issue refers to "object method shorthand", so I also looked into the [syntax of method definition](http://www.ecma-international.org/ecma-262/6.0/#sec-method-definitions) but again found no such limitation. The only thing I managed to find is that you can't name a function `arguments` in strict mode, that is you can't do the following:

```js
function arguments() {}
```

but using `arguments` as a method name should be fine:

```js
obj = { arguments() {} };
```

**Comment by lukeapage** [comment]
Ok, sorry, eslint errord and eslint-import failed to parse because of this. Happy to close
