### ISSUE TITLE
Recognize class inheritance from Node.js util.inherits()?

### ISSUE THREAD

**Issue by apexearth** [mohebifar/lebab#157]
`util.inherits(NewClass, OtherClass)`

**Comment by apexearth** [comment]
I missed that there is presently no support for extending classes.
Are there any plans for it?

**Comment by nene** [comment]
Well... the main problem with inheritance is that there's so many ways to implement it. I don't think there's any single most wide-spread way to implement it... and I'm not even sure what might be the (say, top 10) most wide-spread inheritance implementations.

Like this NodeJS `util.inherits()`... it's the first time I hear about it, but then again I haven't really done a whole lot of NodeJS development.

If you're up for it, we're open for pull requests. Or you could contribute by researching how widespread the use of `util.inherits()` is, so we'd have an actual reason to support it.

**Comment by apexearth** [comment]
I'm willing to give this a try.

I'll start off with implementation for `util.inherits()`.

**Comment by nene** [comment]
Closing this as duplicate in favor of #33
