### ISSUE TITLE
Recent change in recast package removes trailing semi-colons from `export` statements.

### ISSUE THREAD

**Issue by apexearth** [mohebifar/lebab#159]
This went into the 0.11.11 release of recast.
As a result, some of the export tests are now failing due to missing semi-colons. 

See: https://github.com/benjamn/recast/pull/303

**Comment by benjamn** [comment]
Are the test failures meaningful, or just sensitive to the absence of semicolons?

**Comment by apexearth** [comment]
I don't believe they are meaningful, just sensitive to the absence of semicolons.
I'll throw a PR over fixing it here.

**Comment by benjamn** [comment]
Great, that's good to hear. Definitely let me know if the change causes any other problems.

**Comment by nene** [comment]
Thanks to Recast for yet another nice update. And thanks for the PR.
