### ISSUE TITLE
Replace in directory ignores JSX files

### ISSUE THREAD

**Issue by Wilfred** [mohebifar/lebab#163]
I've noticed that 

```
$ ls mydir
foo.js bar.jsx
$ lebab --replace mydir --transform let
```

only applies the transformation on foo.js. 

I can work around this by explicitly running against the JSX file, but I think it's a bug in lebab.

**Comment by nene** [comment]
This is actually by design - it would cause more trouble if Lebab replaced all files, no matter the extension.

Perhaps not well enough documented, but you can tell Lebab to explicitly search for jsx files:

```
$ lebab --replace 'mydir/**/*.jsx' --transform let
```
