### ISSUE TITLE
Transform: indexOf === -1 -> includes

### ISSUE THREAD

**Issue by siddharthkp** [mohebifar/lebab#167]
This is one of my favorite syntactical sugar

```javascript
var months = ['January', 'March', 'July'];  
months.indexOf('March') !== -1;  // true
months.indexOf('August') !== -1; // false
```
to
```javascript
var months = ['January', 'March', 'July'];  
months.includes('March') // true  
months.includes('August') // false
```

More info on [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/includes)

**Comment by nene** [comment]
There are alternative ways of expressing the same as well:

```js
months.indexOf('March') > -1;
months.indexOf('March') >= 0;
```

The nice thing is that this works for both `String` and `Array`. Although interestingly [String.includes][1] is part of ES6 while [Array.includes][2] is in ES7. Therefore this transform would fall under ES7 transforms. It's also not a safe transform as any custom object could potentially have indexOf method - this should be fairly rare though especially as we also take the comparison operator into account.

Overall it looks like a great thing to have.

[string]: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/includes
[array]: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

**Comment by siddharthkp** [comment]
👏
