### ISSUE TITLE
What is the syntax to apply all transformations?

### ISSUE THREAD

**Issue by alexpchin** [mohebifar/lebab#174]
Previously, you could use the syntax:

```
for file in $(find . -name "*.js"); do
  lebab $file -o $file --disable commonjs
done
```

To run all transformations except `commonjs`. However, I don't believe this is the case anymore? Is there an equivalent syntax now?

**Comment by alexpchin** [comment]
I can do: 

```
for transform in arrow for-of arg-spread obj-method obj-shorthand no-strict let template default-param includes 
do
 lebab -t $transform --replace .
done
```

**Comment by nene** [comment]
Yeah, Lebab no more enables all transforms by default. You'll have to explicitly choose which ones you want. This is to encourage the best practice of applying just one transform at a time, inspecting that the result is OK, end then continuing with the next.

But if you really want to you can list multiple transforms by separating them by commas

    lebab -t arrow,let,obj-method --replace .

PS. Note that the transforms get applied in the order you specify which mostly matters for `for-of` transform which only works with let/const variables, so you're better off running `let` transform first.
