### ISSUE TITLE
Reloading Issue

### ISSUE THREAD

**Issue by pertrai1** [mohebifar/lebab#176]
When I type in some code there will be times when the output will not show. The use case most seen is that the first time the code will be transformed, but after the first time this is not the case. Right now I am using it in Safari on Mac.

**Comment by mohebifar** [comment]
I'd appreciate if you provide more details so I can reproduce the issue.

**Comment by pertrai1** [comment]
Sure. If I go and add

```
function test(one, two) {
    return {
        one: 'hi',
        two: 'to',
        three: 'you'
    };
}
````
This will show on the right side how it would look in ES2015. Now if I go and change the code, to say:

```
var testing = 'this is a test';
```
This will not show up on the right side. There is no change to the code on the right side when doing the "TRY IT LIVE"

Hope this gives you enough to reproduce.

**Comment by nene** [comment]
For me it doesn't reproduce. @mohebifar did update the whole site to completely new version, perhaps it happened after you tested.

**Comment by pertrai1** [comment]
@nene @mohebifar Ok, all is good now. Cleared all cache on Chrome and it does not reproduce anymore 👍
