### ISSUE TITLE
function not upgraded to class

### ISSUE THREAD

**Issue by oliversalzburg** [mohebifar/lebab#181]
I have the following code:
```js
"use strict";

const AbstractDataManager = require( "./manager" );
const util                = require( "util" );

function DeviceManager( db ) {
	DeviceManager.super_.call( this, db, "device" );
}

util.inherits( DeviceManager, AbstractDataManager );
```

`DeviceManager` is not upgraded to a class.
```shell
lebab.cmd --transform arrow,class,let,multi-var,template --replace "device.js"
device.js:
6:  warning  Function DeviceManager looks like class, but has no prototype  (class)
```

The file actually has more code, but I reduced it to the essentials. And the behavior is the same with or without the extra code. The omitted code makes explicit references to the prototype though. As in:
```js
DeviceManager.prototype.listByOwner = _.partial( DeviceManager.prototype.listBy, "owner" );
```

**Comment by nene** [comment]
The main problem here is that Lebab does not understand `_.partial()`. This kind of programmatic method creation is hard to convert into ES6 class syntax. Perhaps you'd expect it to become something like:

```js
class DeviceManager {
    listByOwner(...args) {
        return this.listBy("owner", ...args);
    }
}
```

we could write code to make Lebab support this, but it's a very specific case - there are oh-so-many ways to manipulate functions, and often it's hard to tell what should be the equivalent code in ES6.

On the other hand Lebab doesn't even support inheritance yet: #33

The warning message is confusing though and should be improved.

**Comment by oliversalzburg** [comment]
Ah. Well, I would assume some of the problem comes from the missing inheritance support then. I was mostly confused with the warning and why nothing was happening.

The current, manual conversion looks like this:
```
"use strict";

const _                   = require( "lodash" );
const AbstractDataManager = require( "./manager" );
const util                = require( "util" );

class DeviceManager extends AbstractDataManager {
	constructor( db ) {
		super( db, "device" );
	}
}

DeviceManager.prototype.listByOwner            = _.partial( DeviceManager.prototype.listBy, "owner" );
```

So we still just assign to prototype, even though the rest was converted to a class. Spread seems like a great idea, but we're currently on Node 4.5 without flags.
