### ISSUE TITLE
Comments are removed after transpiling

### ISSUE THREAD

**Issue by mdibaiee** [mohebifar/lebab#19]

**Comment by benjamn** [comment]
Shameless plug: issues like this one could be avoided by using https://github.com/benjamn/recast, since it aims to perform non-destructive partial source transformation.

**Comment by runn1ng** [comment]
Not nice, xto6! Not nice! :)

**Comment by nene** [comment]
This has been fixed by switching to recast.

**Comment by nene** [comment]
@mohebifar This has been fixed long time ago.
