### ISSUE TITLE
Line breaks are removed after transpiling

### ISSUE THREAD

**Issue by mdibaiee** [mohebifar/lebab#20]

**Comment by mohebifar** [comment]
Codes converted to ES6 might need a reformation. For instance, keeping the exact linebreaks after prototype assignment closing brace for class methods is not easy. So I think formatting the codes can be a solution.

**Comment by benjamn** [comment]
Shameless plug: issues like this one could be avoided by using https://github.com/benjamn/recast, since it aims to perform non-destructive partial source transformation.

**Comment by mohebifar** [comment]
@benjamn This is awesome. :+1:
