### ISSUE TITLE
Support callee default parameters

### ISSUE THREAD

**Issue by mohebifar** [mohebifar/lebab#29]
There are several ways to define default parameters.

```js
function (a, b, c, d) {
   a = a || 1; // 1 is a default value
   b = typeof b !== 'undefined' ? b : 2; // 2 is a default value
   c = typeof c === 'undefined' ? 3 : c; // 3 is a default value
   d = d ? d : 4; // 4 is a default value
}
```

And it should be converted to :
```js
function (a = 1, b = 2, c = 3, d = 4) {

}
```

**Comment by mdibaiee** [comment]
I think we can take steps to implement each style separately, We see the first style most of the time, others are pretty rare.

**Comment by mdibaiee** [comment]
`a || 1` works now. See commit 8dcfed4

**Comment by nene** [comment]
All 4 styles are now supported.
