### ISSUE TITLE
Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by masklinn** [mohebifar/lebab#54]
Related to #53, I tried to "fix" the issue by converting the property reference to a dynamic name instead of renaming it entirely:
```javascript
function foo(b) {
    var a = 3;
    b['a'] = 42;
}
```
In the online converter of the home page, this fails with the following trace:
```
TypeError: Attempted to assign to readonly property.
d app.js:21:25701
__execute app.js:18:981
traverse app.js:18:1755
n app.js:17:26082
exports app.js:21:25824
value app.js:21:28633
value app.js:21:28786
transpile app.js:1:103
(anonymous function) app.js:21:30880
```

**Comment by nene** [comment]
Fixed by #73, and later further fixed by complete rewrite of the let-transform.
