### ISSUE TITLE
Source JavaScript used on xto6.js.org example contains an error

### ISSUE THREAD

**Issue by philberesford** [mohebifar/lebab#56]
It's just a low priority issue on the homepage of http://xto6.js.org/

The source JavaScript in the example transpilation contains an error:

```javascript
Person.prototype.getAge = function (birthYear) {
  var age = 2015;
  age -= birthYear;

  return result;
};
```

which should be

```javascript
Person.prototype.getAge = function (birthYear) {
  var age = 2015;
  age -= birthYear;

  return age;
};
```

**Comment by crcastle** [comment]
Also this is incorrect, and I'm not sure what it was meant to be:
```javascript
Object.defineProperty(Person.prototype, 'age', {
  get: function () {
    return this.getAge();
  }
});
```
The `getAge()` function call needs a parameter `birthYear` otherwise you get `NaN`.

**Comment by nene** [comment]
@mohebifar, what's the story with xto6.js.org site? Shouldn't it be redirected to lebab.io?

Similarly there's [xto6](https://www.npmjs.com/package/xto6) package available on npm. It should be deprecated to direct users to lebab instead:

- [Deprecate a version of a package](https://docs.npmjs.com/cli/deprecate)

**Comment by nene** [comment]
xto6.js.org site has now been redirected to lebab.io.
