### ISSUE TITLE
Syntax highlighting on xto6 website

### ISSUE THREAD

**Issue by hex13** [mohebifar/lebab#57]
On the project's webiste http://xto6.js.org "better" transpiled code looks actually uglier because of lack of syntax highlighting for ES6 on the right pane. Maybe some plugin for Ace could make it better?

PS. I know that this is not related with project itself and this is maybe not super important, but it just looks ugly ;)

**Comment by mohebifar** [comment]
Thanks for opening an issue. Please check the [new REPL](http://lebab.io/try-it).
