### ISSUE TITLE
Live Transpile on Front Page Fails (Doesn't Like ||?)

### ISSUE THREAD

**Issue by machineghost** [mohebifar/lebab#58]
I recently tried to use your live transpile feature, but got the following error:

    Uncaught TypeError: Cannot set property 'kind' of undefined

Here's the full stack trace (although it's probably useless because of the minification):

    Uncaught TypeError: Cannot set property 'kind' of undefinedd @ app.js:22k.__execute @ app.js:19k.traverse @ app.js:19n @ app.js:18b.exports @ app.js:22e.applyTransformation.value @ app.js:22e.applyTransformations.value @ app.js:22transpile @ app.js:1(anonymous function) @ app.js:22setTimeout (async)(anonymous function) @ app.js:22d._signal @ vendor.js:3(anonymous function) @ vendor.js:11d @ vendor.js:3setTimeout (async)e @ vendor.js:3(anonymous function) @ vendor.js:11d._signal @ vendor.js:3onDocumentChange @ vendor.js:11d._signal @ vendor.js:3onChange @ vendor.js:10d._signal @ vendor.js:3removeInLine @ vendor.js:8remove @ vendor.js:8remove @ vendor.js:10insert @ vendor.js:12onPaste @ vendor.js:12K @ vendor.js:3

I tried simplifying my code until I got down to:

    var NodeView = function(mode) {
        var self = this;
        self.mode = mode || 'foo';  
    };

If I removed the line with `||` it was able to transpile, so it seems the tool has an issue with boolean logic.

**Comment by mohebifar** [comment]
The problem does not exist in `master` branch. I will update `gh-pages` soon.

**Comment by voronianski** [comment]
@machineghost same for me

**Comment by mohebifar** [comment]
@voronianski, @machineghost It's been fixed on the [new REPL](http://lebab.io/try-it). Thank you!

**Comment by machineghost** [comment]
Thanks!
