### ISSUE TITLE
Support stdout/stdin as output/input file

### ISSUE THREAD

**Issue by dbkaplun** [mohebifar/lebab#61]
Looks like the relevant code is [here](https://github.com/mohebifar/lebab/blob/bfac0ab8e6a6bcd824379c4981c31b7d99132aac/src/transformer.js#L118-L136) for stdout and [here](https://github.com/mohebifar/lebab/blob/aeeb2fed0846f3cbdf7a7f8768ae454feee29b4a/src/utils/ast-generator.js#L6-L31) for stdin. Maybe `-` could be replaced with a stdout/in operation, as it is a convention for both stdin and stdout in many Unix programs.

**Comment by nene** [comment]
It would make most sense to simply read from STDIN when no input files given, and write to STDOUT when no `--out-file` option specified.
