### ISSUE TITLE
Option to output to STDOUT

### ISSUE THREAD

**Issue by aziz** [mohebifar/lebab#64]
I'm planning to integrate this awesome tool into my editor and having the option to run the command and read the STDOUT output would make it much easier. 
Sticking to UNIX paradigms would help us to pipe the output to other commands as well. 

Make it a UNIXy tool please. 

great job btw :+1:

**Comment by dbkaplun** [comment]
+1 and stdin as well!

**Comment by nene** [comment]
I just ran lebab for the first time and was quite surprised that it decided to pick a filename `output.js` instead of sensibly writing it STDOUT.

**Comment by rahul26goyal** [comment]
@mohebifar .. Can we add a check to see of there is an existing file with its name 'output.js'. If there is, we prompt user to provide a different output file or replace the existing one.

**Comment by nene** [comment]
Related to #61 and #70.

**Comment by nene** [comment]
What about closing this issue?
