### ISSUE TITLE
Leading and trailing whitespace is not preserved

### ISSUE THREAD

**Issue by nene** [mohebifar/lebab#81]
Similarly to #20 (which seems to be fixed), but only affects the whitespace at the beginning and end of a file. Especially annoying if you follow the rule of ending each file with a newline.

This happens because of the following line in `ast-generator`:

```js
let ast = recast.parse(js).program;
```

Here we only take the `program`-part of the AST generated by Recast, throwing away the surrounding `File` node that contains information about this additional whitespace. The likely reason for throwing it away is that other AST-analyzers like ESTraverse don't recognize the `File` node and will choke for it. So we can either hide this node from them or configure them to recognize it - but we need to preserve it somehow.

**Comment by dgreensp** [comment]
I'd love a new NPM release with this fix!
