### ISSUE TITLE
Please, close resolved issues

### ISSUE THREAD

**Issue by nene** [mohebifar/lebab#93]
There are lots of issues that have been resolved or have become irrelevant:

- #86 Upgrade of estraverse is broken on windows (This bug report looks outdated, as it's reported for `xto6` not `lebab`. There's been no further interest from the reporter as well.)
- #69 Future Roadmap
- #64 Option to output to STDOUT enhancement
- #62 Large amount of errors (duplicates other more specific issues)
- #32 Switch to benjamn/recast
- #20 Line breaks are removed after transpiling
- #12 Convert commonjs module definitions (This is now implemented, it can be improved further, but the most common use case is covered.)
- #1 Possible merge with 5to6? (Doesn't look really feasable, all features except AMD transform already implemented in Lebab).

Also this pull request:

- #70 Feature Enhancement: --stdout option added to Output result to STDOUT 

The repo would look much cleaner without all this noise.

**Comment by mohebifar** [comment]
Thank you.
